config/urls.py
from django.views.generic import RedirectView
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', RedirectView.as_view(url='library/', permanent=True)),
    path('admin/', admin.site.urls),
    path('library/', include('library.urls')),
    path('membership/', include('membership.urls')),
]

library/urls.py
from django.urls import path
from . import views
from membership import views as membershipview
# URL PATTERNS

urlpatterns = [
    path('', views.index, name="index"),
    path('authors/', views.AuthorListView.as_view(), name="author-list"),
    path('books/', views.BookListView.as_view(), name="book-list"),
    path('authors/<int:pk>', views.AuthorDetailView.as_view(), name="author-detail"),
    path('books/<int:pk>', views.BookDetailView.as_view(), name="book-detail"),
]

library/models.py
from django.db import models
from django.urls import reverse
import uuid
# Create your models here.


class Author(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)

    def get_absolute_url(self):
        return reverse("author-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'


class Book(models.Model):
    TYPE_CHOICES = (
        ('BO', 'Book'),
        ('MA', 'Magazine')
    )
    type = models.CharField(max_length=2, default='BO', blank=True, null=True)
    title = models.CharField(max_length=255)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    first_published = models.CharField(
        max_length=4, help_text="Enter year in format YYYY. Must be four digits", blank=True, null=True)

    summary = models.TextField(default="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", blank=True, null=True)

    def get_absolute_url(self):
        return reverse("book-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title


class BookInstance(models.Model):
    STATUS_CHOICES = (
        ('A', 'Available'),
        ('N', 'Not available')
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    publisher = models.CharField(max_length=255, blank=True, null=True)
    edition = models.CharField(max_length=255)
    status = models.CharField(
        max_length=1, choices=STATUS_CHOICES, default='A')

    def __str__(self):
        return self.book.title

library/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Author, Book, BookInstance

# Create your views here.


class BookDetailView(DetailView):
    model = Book


class AuthorDetailView(DetailView):
    model = Author


class BookListView(ListView):
    model = Book
    template_name = 'book_list.html'
    paginate_by = 10


class AuthorListView(ListView):
    model = Author
    template_name = 'article_list.html'
    paginate_by = 10


def index(request):
    num_authors = Author.objects.count()
    num_books = Book.objects.count()
    num_available_books = BookInstance.objects.filter(status='A').count()
    context = {
        'num_authors': num_authors,
        'num_books': num_books,
        'num_available_books': num_available_books
    }
    return render(request, 'library/index.html', context=context)

library/templates/library/author_detail.html
{% extends 'base.html' %}
{% block content %}
{% if object %}
<div class="">
	<h4>{{ object.first_name }} {{ object.last_name }}</h4>
</div>
<div class="">
</div>
<div class="">
	<p>Authorship:</p>
	<ul>
		{% for book in author.book_set.all %}
		<li>
			<a href="{% url 'book-detail' book.pk %}">
				{{book.title}}
			</a>
			<span>
				{{book.first_published}} - ({{ book.bookinstance_set.count }})
			</span>
		</li>
		{% endfor %}
	</ul>
</div>
{% endif %}
{% endblock %}

library/templates/library/author_list.html
{% extends 'base.html' %}

{% block content %}
{% if object_list %}
<h2 class="">All authors:</h2>
<ul class="">
	{% for author in object_list %}
	<li class="">
		<a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{ author.last_name }}</p>
	</li>
	{% endfor %}
</ul>
{% endif %}
{% endblock %}

library/templates/library/book_detail.html
{% extends 'base.html' %}
{% block content %}
{% if object %}
<div class="">
	<h4>{{ object.title }}, {{ object.first_published }}</h4>
</div>
<div class="mb-3">
	<small class="muted">Author:
		<a href="{% url 'author-detail' book.author.pk %}">{{ object.author }}</a>
	</small>
</div>
<div class="mb-3">
	<p>{{ object.summary }}</p>
</div>
<div class="mb-3">
	<p>MyLibrary has {{ object.bookinstance_set.count }} copies of "{{object.title}}":</p>
	{% for copy in object.bookinstance_set.all %}
	<div class="book-instance">
		<strong>{{ copy.book }}</strong>
		<ul>
			<li>Publisher: {{copy.publisher}}</li>
			{% if copy.status != 'A' %}
			<li>
				<small class="text-secondary">This copy is not available</small>
			</li>
			{% endif %}
		</ul>
	</div>
	{% endfor %}
</div>

{% endif %}
{% endblock %}

library/templates/library/book_list.html
{% extends 'base.html' %}

{% block content %}
{% if object_list %}
<h2 class="">All titles:</h2>
<ul class="">
	{% for book in object_list %}
	<li class="">
		<a href="{{ book.get_absolute_url }}">{{ book.title }}</p>
	</li>
	{% endfor %}
</ul>
{% endif %}
{% endblock %}

library/templates/library/index.html
{% extends 'base.html' %}
{% block content %}

<div class="text-break">
	We currently have <span class="strong">{{ num_authors }}</span> authors represented. Our catalog has <span
		class="strong">{{ num_books }}</span> different titles and <span class="strong">{{ num_available_books }}
		available books right now.</span>
</div>

{% endblock %}